# -*- coding: utf-8 -*-
"""Governança de Dados - pratica 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BU7YkInaF4fb3a0U2z_EE_2rTcjw6UKp
"""

import pandas as pd
from pandas_profiling import ProfileReport

df = pd.read_csv("/content/base.csv", delimiter=';')

display(df)

profile = ProfileReport(df, title="Profiling base bolsa família", html={"style":{"full_width":True}})

profile.to_file("profiling_base_bolsa_familia.html")